import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

/**
 * ESLint flat config.
 *
 * `next lint` is deprecated in Next 15 and, with no config file present, it
 * dropped into an interactive setup prompt — which is why `bun run lint` hung
 * and exited 1 in CI and in any non-TTY shell. The script now calls the ESLint
 * CLI directly against this file.
 *
 * eslint-config-next 15.5 still ships only the legacy (eslintrc) format, so
 * FlatCompat translates it. It can be dropped for a direct import once that
 * package publishes a flat config export.
 */
const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

export default [
  {
    ignores: [
      '.next/**',
      'out/**',
      'build/**',
      'next-env.d.ts',
      // Generated by `bun run sync:types` in horo-be — fix lint problems at the
      // source there, never here, or the next sync silently reverts them.
      'src/lib-packages/**',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
];
